spring.application.name=notification-service
server.port=9999

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#curl http://localhost:9999/health

twilio.account.sid=ACd8745817a4136d8ccce18513011e3ec9
twilio.auth.token=444813512402d54c110c2cda482948a5
twilio.phone.number=+15005550006


# Logging
logging.level.com.example.notificationservice=DEBUG