
spring.application.name=apiGatewayy
server.port=8083


# ============================================
# Eureka
# ============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# ============================================
# COURSE SERVICE ROUTE
# ============================================
spring.cloud.gateway.routes[0].id=course-service
spring.cloud.gateway.routes[0].uri=lb://course-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/courses/** , /api/students/** , /timetable/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=courseServiceCB,fallbackUri=forward:/fallback/course

# ============================================
# TEACHER SERVICE ROUTE
# ============================================
#spring.cloud.gateway.routes[1].id=teacher-service
#spring.cloud.gateway.routes[1].uri=lb://teacher-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/teacher/**,/teacher
#spring.cloud.gateway.routes[1].filters[1]=RewritePath=/teacher/(?<segment>.*), /$\{segment}
#spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=teacherServiceCB,fallbackUri=forward:/fallback/teacher
spring.cloud.gateway.routes[1].id=teacher-service
spring.cloud.gateway.routes[1].uri=lb://teacher-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/teacher/**,/teacher
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=teacherServiceCB,fallbackUri=forward:/fallback/teacher
# ============================================
# RESILIENCE4J - COURSE
# ============================================
resilience4j.circuitbreaker.instances.courseServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.courseServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.courseServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.courseServiceCB.wait-duration-in-open-state=10s

# ============================================
# RESILIENCE4J - TEACHER
# ============================================
resilience4j.circuitbreaker.instances.teacherServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.teacherServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.teacherServiceCB.failure-rate-threshold=40
resilience4j.circuitbreaker.instances.teacherServiceCB.wait-duration-in-open-state=8s

# ============================================
# ACTUATOR
# ============================================
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

# ============================================
# LOGGING
# ============================================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.io.github.resilience4j=DEBUG

spring.cloud.config.enabled=false

# ============================================
# AUTH SERVICE ROUTE
# ============================================
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**,/users/** , /users
#  spring.cloud.gateway.routes[2].predicates[1]=Path=/users/**
#
#spring.cloud.gateway.routes[2].id=auth-service
#spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**